name: Build

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
jobs:
  get_pull_requests:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Report
        run:  echo "Building..."
