name: Merge main into PR branches labeled "automerge main"

on:
  push:
    branches:
      - "automerge/*"
  pull_request:
    branches:
      - "automerge/*"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: master
          target_branch: ${{ github.ref }}
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
