name: Merge main into PR branches labeled "automerge main"

on:
  push:
    branches:
      - master
jobs:
  get_pull_requests:
    runs-on: ubuntu-latest
    name: Show pull requests
    steps:
      - uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{github.token}}
          labels: '[]'
          skip_hour: ''
      - run: echo '${{ steps.list.outputs.pulls }}'
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ steps.list.outputs.pulls }}'
