name: Merge main into PR branches labeled "automerge main"
on:
  pull_request:
    types: [labeled]
    branches: "automerge/*"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.4.0
        with:
          label_name: 'automerge main'
          from_branch: 'main'
          github_token: ${{ github.token }}
